### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by povilasb** [redox-os/bootloader#1]
See: https://github.com/redox-os/bootloader/blob/master/x86_64/print16.asm

```asm
; print a string and a newline
; IN
;   si: points at zero-terminated String
; CLOBBER
;   ax
print_line:
    mov al, 13
    call print_char
    mov al, 10
    jmp print_char
```

This function ignores documented parameter `si` 
> si: points at zero-terminated String

and prints new line only.

**Comment by jackpot51** [comment]
Fixed
